### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rubenwardy** [antrad/If_Quake_2_Was_2D#1]
You haven't included a license, which makes it all rights reserved by default. This means that we can't fork it and make fixes or improvements.

**Comment by antrad** [comment]
But it says in the readme "for educational and non-commercial use only", I think that is clear enough.

It says in the GitHub Help articles that "if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository." which should mean you are able to fork it. If I have to enable/disable it somewhere let me know, because I'm not very familiar how things work here.

**Comment by rubenwardy** [comment]
http://choosealicense.com/ may be useful

**Comment by antrad** [comment]
I FINALLY included the license information in the repository. Please read LICENSE and LICENSE.WTFPL for more info. In short; as long as you don't publish it in a book, you are safe to do whatever you want.
